{{- if or ( contains "microsoft.kubernetes/connectedclusters" (.Values.Azure.Cluster.ResourceId | lower) ) ( contains "microsoft.kubernetes/connectedclusters" (.Values.omsagent.env.clusterId | lower)) }}
apiVersion: clusterconfig.azure.com/v1beta1
kind: AzureExtensionIdentity
metadata:
  name: {{ .Values.Azure.Extension.ResourceName }}
  namespace: azure-arc
spec:
  serviceAccounts:
    - name: omsagent
      namespace: kube-system
  tokenNamespace: azure-arc
---
apiVersion:  clusterconfig.azure.com/v1beta1
kind: AzureClusterIdentityRequest
metadata:
  name: container-insights-clusteridentityrequest
  namespace: azure-arc
spec:
  audience: https://monitoring.azure.com/
  resourceId: {{ .Values.Azure.Extension.ResourceName }} 
{{- end }}
