receivers:
  opencensus:
    endpoint: 0.0.0.0:55678
processors:
  batch:
  queued_retry:
extensions:
  health_check:
exporters:
  azuremonitor:
    # endpoint is the uri used to communicate with Azure Monitor
    endpoint: "https://dc.services.visualstudio.com/v2/track"
    # instrumentation_key is the unique identifer for your Application Insights resource
    instrumentation_key: c7bd3894-56c1-47d7-a8e6-98440e2018b6
    # maxbatchsize is the maximum number of items that can be queued before calling to the configured endpoint
    maxbatchsize: 100
    # maxbatchinterval is the maximum time to wait before calling the configured endpoint.
    maxbatchinterval: 10s
  logging:
    # loglevel: debug
service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [opencensus]
      processors: [batch, queued_retry]
      exporters: [azuremonitor, logging]
