exporters:
  file:
    path: /opt/promotel.json
  #logging:
    #loglevel: debug
  prometheus:
    endpoint: "0.0.0.0:9999"
  influx:
    loglevel: debug
receivers:
    prometheus:
      config:
        global:
          evaluation_interval: 30s
          scrape_interval: 30s
          external_labels:
            prometheus: monitoring2/prometheus-release-1-prome-prometheus
            prometheus_replica: prometheus-prometheus-release-1-prome-prometheus-0
        scrape_configs:
        - job_name: apiserver
          scheme: https
          kubernetes_sd_configs:
          tls_config:
            insecure_skip_verify: true
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          static_configs:
           - targets: [$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT]
             labels:
               job: apiserver
service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [file,prometheus,influx]